// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_9V6gSpoR03Dt5cz6ttEy8_U7Em5XOOk',
    appId: '1:515960756558:android:058487c80d41d2e32ea61f',
    messagingSenderId: '515960756558',
    projectId: 'chatter-fc1af',
    storageBucket: 'chatter-fc1af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2EWmlvCS7rBfy_-tRBuNXkyJJP5gbARk',
    appId: '1:515960756558:ios:c279d95ef645a92d2ea61f',
    messagingSenderId: '515960756558',
    projectId: 'chatter-fc1af',
    storageBucket: 'chatter-fc1af.appspot.com',
    androidClientId: '515960756558-i21q2q8bdhgk9ra2niusiofv8ogefp4u.apps.googleusercontent.com',
    iosClientId: '515960756558-ufrgu7gpov0h0li4f75q20g1q3oh2htd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatter',
  );
}
